apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: registry.redhat.io/rhel10/postgresql-16
        ports:
        - containerPort: 5432
        env:
        - name: TZ
          value: Europe/Madrid
        - name: POSTGRESQL_DATABASE
          value: coolstore
        - name: POSTGRESQL_USER
          value: quarkus
        - name: POSTGRESQL_PASSWORD
          value: quarkus
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresql-data
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: postgres-pvc
